"use client";

/**
 * components/civic/eligibility-indicator.tsx
 *
 * EligibilityBadge and EligibilitySummary components for Vayam.
 * Displays structured eligibility results generated by the Civic Intelligence layer.
 */

import React from "react";
import { cn } from "@/lib/utils/cn";
import { CheckCircle2, AlertTriangle, XCircle, HelpCircle, Info } from "lucide-react";
import type { EligibilityStatus } from "@/types/civic";

export interface EligibilityBadgeProps {
  status: EligibilityStatus | "LIKELY_ELIGIBLE" | "MAYBE_ELIGIBLE" | "NOT_ELIGIBLE" | "NOT_YET" | "UNKNOWN";
  className?: string;
}

export function EligibilityBadge({ status, className }: EligibilityBadgeProps) {
  const statusKey = String(status).toLowerCase();

  const config = {
    eligible: {
      class: "badge-eligible",
      icon: <CheckCircle2 size={12} />,
      label: "✓ Eligible",
    },
    likely_eligible: {
      class: "badge-eligible",
      icon: <CheckCircle2 size={12} />,
      label: "✓ Likely Eligible",
    },
    requires_verification: {
      class: "badge-maybe",
      icon: <AlertTriangle size={12} />,
      label: "⚠ Needs Verification",
    },
    maybe_eligible: {
      class: "badge-maybe",
      icon: <AlertTriangle size={12} />,
      label: "⚠ Maybe Eligible",
    },
    ineligible: {
      class: "badge-ineligible",
      icon: <XCircle size={12} />,
      label: "✕ Not Eligible",
    },
    not_eligible: {
      class: "badge-ineligible",
      icon: <XCircle size={12} />,
      label: "✕ Not Eligible",
    },
    not_yet: {
      class: "badge-blue",
      icon: <Info size={12} />,
      label: "⌛ Not Yet Eligible",
    },
    unknown: {
      class: "badge-muted",
      icon: <HelpCircle size={12} />,
      label: "Status Unknown",
    },
  }[statusKey] || {
    class: "badge-muted",
    icon: <HelpCircle size={12} />,
    label: String(status),
  };

  return (
    <span className={cn("badge", config.class, className)}>
      {config.icon}
      <span>{config.label}</span>
    </span>
  );
}

export interface EligibilitySummaryProps {
  status: EligibilityStatus;
  reasons?: string[];
  missingFields?: string[];
  className?: string;
}

export function EligibilitySummary({
  status,
  reasons = [],
  missingFields = [],
  className,
}: EligibilitySummaryProps) {
  return (
    <div
      className={cn(
        "p-4 rounded-xl border space-y-3",
        status === "eligible"
          ? "bg-success-subtle border-success/30 text-foreground"
          : status === "requires_verification"
          ? "bg-warning-subtle border-warning/30 text-foreground"
          : "bg-surface-secondary border-border-subtle text-foreground",
        className
      )}
    >
      <div className="flex items-center justify-between">
        <span className="text-label font-bold uppercase tracking-wider">
          Eligibility Breakdown
        </span>
        <EligibilityBadge status={status} />
      </div>

      {reasons.length > 0 && (
        <ul className="space-y-1.5 text-body-sm list-disc list-inside text-muted-foreground">
          {reasons.map((reason, i) => (
            <li key={i} className="text-foreground">{reason}</li>
          ))}
        </ul>
      )}

      {missingFields.length > 0 && (
        <div className="pt-2 border-t border-border-subtle/50 text-caption text-muted-foreground">
          <span className="font-semibold text-warning">Information needed: </span>
          <span>{missingFields.join(", ")}</span>
        </div>
      )}
    </div>
  );
}
